-- Insert all remaining missing French translations from the network requests
INSERT INTO website_translations (original_text, translated_text, target_language, page_path, source_language, is_active) VALUES
('Visual Learning Revolution', 'Révolution de l''Apprentissage Visuel', 'fr', '/', 'en', true),
('Master complex business concepts through stunning visual content designed by learning experts and cognitive scientists.', 'Maîtrisez des concepts commerciaux complexes grâce à un contenu visuel époustouflant conçu par des experts en apprentissage et des scientifiques cognitifs.', 'fr', '/', 'en', true),
('Micro-Learning Magic', 'Magie du Micro-Apprentissage', 'fr', '/', 'en', true),
('Transform your career with bite-sized 5-minute lessons that fit perfectly into your busy professional schedule.', 'Transformez votre carrière avec des leçons de 5 minutes qui s''intègrent parfaitement dans votre emploi du temps professionnel chargé.', 'fr', '/', 'en', true),
('Gamified Achievement', 'Réalisation Gamifiée', 'fr', '/', 'en', true),
('Unlock leagues, earn prestigious certificates, and build an impressive professional portfolio that stands out.', 'Débloquez des ligues, gagnez des certificats prestigieux et construisez un portfolio professionnel impressionnant qui se démarque.', 'fr', '/', 'en', true),
('Success Stories', 'Histoires de Réussite', 'fr', '/', 'en', true),
('Professionals transformed', 'Professionnels transformés', 'fr', '/', 'en', true),
('Expert Rating', 'Évaluation d''Expert', 'fr', '/', 'en', true),
('Based on 2,847 reviews', 'Basé sur 2 847 avis', 'fr', '/', 'en', true),
('Average Lesson', 'Leçon Moyenne', 'fr', '/', 'en', true),
('Career Growth', 'Croissance de Carrière', 'fr', '/', 'en', true),
('Within 6 months', 'En 6 mois', 'fr', '/', 'en', true),
('Start Your Journey FREE', 'Commencez Votre Parcours GRATUITEMENT', 'fr', '/', 'en', true),
('Watch Success Stories', 'Regarder les Histoires de Réussite', 'fr', '/', 'en', true),
('2 min preview', 'Aperçu de 2 min', 'fr', '/', 'en', true),
('Ready to Transform', 'Prêt à Transformer', 'fr', '/', 'en', true),
('Why', 'Pourquoi', 'fr', '/', 'en', true),
('10,000+ Professionals', '10 000+ Professionnels', 'fr', '/', 'en', true),
('Choose Us', 'Nous Choisissent', 'fr', '/', 'en', true),
('Experience the future of business education with our revolutionary visual learning platform', 'Découvrez l''avenir de l''éducation commerciale avec notre plateforme d''apprentissage visuel révolutionnaire', 'fr', '/', 'en', true),
('Visualize Your', 'Visualisez Votre', 'fr', '/', 'en', true),
('AI-powered visual learning that transforms complex concepts into memorable experiences', 'Apprentissage visuel alimenté par l''IA qui transforme les concepts complexes en expériences mémorables', 'fr', '/', 'en', true),
('Limited Time Opportunity', 'Opportunité à Durée Limitée', 'fr', '/', 'en', true),
('Your Competition is', 'Votre Concurrence', 'fr', '/', 'en', true),
('Learning Right Now', 'Apprend Maintenant', 'fr', '/', 'en', true),
('While you''re thinking about it, thousands of professionals are already advancing their careers. Don''t let this moment pass—your future self will thank you.', 'Pendant que vous y réfléchissez, des milliers de professionnels font déjà progresser leur carrière. Ne laissez pas passer ce moment - votre futur moi vous remerciera.', 'fr', '/', 'en', true),
('Students enrolled this week', 'Étudiants inscrits cette semaine', 'fr', '/', 'en', true),
('Got promoted within 6 months', 'Ont été promus en 6 mois', 'fr', '/', 'en', true),
('Real results, real careers', 'Vrais résultats, vraies carrières', 'fr', '/', 'en', true),
('Left to claim your FREE access', 'Restant pour réclamer votre accès GRATUIT', 'fr', '/', 'en', true),
('After that, it''s $97/month', 'Après cela, c''est 97$/mois', 'fr', '/', 'en', true),
('Trusted by', 'Approuvé par', 'fr', '/', 'en', true),
('Industry Leaders', 'Leaders de l''Industrie', 'fr', '/', 'en', true),
('Join professionals from Fortune 500 companies who''ve transformed their careers', 'Rejoignez des professionnels d''entreprises du Fortune 500 qui ont transformé leur carrière', 'fr', '/', 'en', true),
('Like a', 'Comme un', 'fr', '/', 'en', true),
('10,000+ professionals', '10 000+ professionnels', 'fr', '/', 'en', true),
('who mastered business fundamentals through our', 'qui ont maîtrisé les fondamentaux commerciaux grâce à notre', 'fr', '/', 'en', true),
('revolutionary visual learning system', 'système d''apprentissage visuel révolutionnaire', 'fr', '/', 'en', true),
('nav.programs', 'Programmes', 'fr', '/', 'en', true),
('nav.visual', 'Visuel', 'fr', '/', 'en', true),
('nav.business', 'Business', 'fr', '/', 'en', true),
('nav.getStarted', 'Commencer', 'fr', '/', 'en', true)
ON CONFLICT (original_text, target_language, page_path) DO UPDATE SET
translated_text = EXCLUDED.translated_text,
is_active = true,
updated_at = now();